hello_the_world:
     path:    /hello-world
     defaults: { _controller: VCPlatformBundle:Advert:index }

goodbye_the_world:
     path:    /goodbye
     defaults: { _controller: VCPlatformBundle:Advert:goodbye }
