
# src/OC/PlatformBundle/Resources/config/routing.yml

vc_platform_home:
    path:      /{page}
    defaults:
        _controller: VCPlatformBundle:Advert:index
        page:    1
    requirements:
        page: \d+

vc_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: VCPlatformBundle:Advert:view
    requirements:
        id: \d+

vc_platform_add:
    path:      /add
    defaults:
        _controller: VCPlatformBundle:Advert:add

vc_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: VCPlatformBundle:Advert:edit
    requirements:
        id: \d+

vc_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: VCPlatformBundle:Advert:delete
    requirements:
        id: \d+

vc_platform_purge:
    path:     /purge/{days}
    defaults:
        _controller: VCPlatformBundle:Advert:purge
    requirements:
        days: \d+
