# src/OC/PlatformBundle/Resources/config/services.yml

services:

  vc_platform.antispam:
      class: VC\PlatformBundle\Antispam\VCAntispam
      arguments:
          - "@mailer"
          - %locale%
          - 50

  vc_platform.email.application_mailer:
      class: VC\PlatformBundle\Email\ApplicationMailer
      arguments:
          - "@mailer"

  vc_platform.doctrine_listener.application_creation:
    class: VC\PlatformBundle\DoctrineListener\ApplicationCreationListener
    arguments:
      - "@vc_platform.email.application_mailer"
    tags:
      - { name: doctrine.event_listener, event: postPersist }

  vc_platform.validator.antiflood:                             # lenom du service
    class: VC\PlatformBundle\Validator\AntifloodValidator    # La classe du service, ici notre validateur déjà créé
    arguments: ["@request_stack", "@doctrine.orm.entity_manager"] # Les données qu'on injecte au service : la requête et l'entity_manager
    tags:
        - { name: validator.constraint_validator, alias: vc_platform_antiflood } # c'est avc l'alias qu'on retrouvera le service
