# src/OC/PlatformBundle/Resources/config/services.yml

services:
  vc_platform.antispam:
      class: VC\PlatformBundle\Antispam\VCAntispam
      arguments:
          - "@mailer"
          - %locale%
          - 50

  vc_platform.email.application_mailer:
      class: VC\PlatformBundle\Email\ApplicationMailer
      arguments:
          - "@mailer"

  vc_platform.doctrine_listener.application_creation:
    class: VC\PlatformBundle\DoctrineListener\ApplicationCreationListener
    arguments:
      - "@vc_platform.email.application_mailer"
    tags:
      - { name: doctrine.event_listener, event: postPersist }
